// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJJIuOpScCNLLrFyp6hOpqXtquOrpQCco',
    appId: '1:500076235973:web:2fdb3f51c33bad48e874ac',
    messagingSenderId: '500076235973',
    projectId: 'petapp-126db',
    authDomain: 'petapp-126db.firebaseapp.com',
    storageBucket: 'petapp-126db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP5VSQQJ_Tv2qM5mCffIy-m1rr9jhcq0w',
    appId: '1:500076235973:android:3f55607596b44349e874ac',
    messagingSenderId: '500076235973',
    projectId: 'petapp-126db',
    storageBucket: 'petapp-126db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lqXTb3G0w10vsaII31102W-5aVgZG40',
    appId: '1:500076235973:ios:46af158babb79b97e874ac',
    messagingSenderId: '500076235973',
    projectId: 'petapp-126db',
    storageBucket: 'petapp-126db.firebasestorage.app',
    iosBundleId: 'com.example.docapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_lqXTb3G0w10vsaII31102W-5aVgZG40',
    appId: '1:500076235973:ios:46af158babb79b97e874ac',
    messagingSenderId: '500076235973',
    projectId: 'petapp-126db',
    storageBucket: 'petapp-126db.firebasestorage.app',
    iosBundleId: 'com.example.docapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJJIuOpScCNLLrFyp6hOpqXtquOrpQCco',
    appId: '1:500076235973:web:6b4f94a2455ec9dee874ac',
    messagingSenderId: '500076235973',
    projectId: 'petapp-126db',
    authDomain: 'petapp-126db.firebaseapp.com',
    storageBucket: 'petapp-126db.firebasestorage.app',
  );
}
